-- Helikon.IA — seed generado desde graph-data.json

insert into nodos (id, numero, nombre, rama, objetivo, construir, romper, resolver) values
('L', 1, 'Lógica de programación', 'Fundamentos', 'Resolver problemas con condicionales y loops', '5 problemas cortos (ej. FizzBuzz)', 'Casos límite: negativos, cero, texto en vez de número', 'Por qué validar el tipo de dato antes de operar'),
('V', 2, 'Variables y control de flujo', 'Fundamentos', 'Manejar reglas anidadas de decisión', 'Programa que calcula descuentos con reglas anidadas', 'Condiciones contradictorias, loops infinitos', 'Orden de evaluación, por qué un loop no termina'),
('F', 3, 'Funciones y estructuras de datos', 'Fundamentos', 'Procesar listas de datos con funciones', 'Función que procesa pedidos y devuelve totales', 'Lista vacía, datos duplicados, tipos mezclados', 'Por qué separar responsabilidades evita bugs en cadena'),
('POO', 4, 'Programación orientada a objetos', 'Fundamentos', 'Modelar entidades del mundo real como clases', 'Clases Usuario y Pedido con métodos', 'Herencia mal diseñada que rompe un caso no previsto', 'Composición vs herencia'),
('REQ', 37, 'Ingeniería de requerimientos', 'Diseño y requerimientos', 'Transformar una necesidad del cliente en requisitos claros y verificables', 'Historias de usuario y criterios de aceptación para un pedido ambiguo', 'El cliente pide algo contradictorio ("que sea rápido y guarde todo el historial")', 'Por qué un requisito ambiguo genera bugs de diseño, no de código'),
('DIS', 38, 'Diseño de software', 'Diseño y requerimientos', 'Traducir requisitos en una estructura concreta antes de programar', 'Diagramar componentes y su comunicación para el sistema de pedidos', 'Dos componentes que deberían estar separados terminan mezclados (acoplamiento)', 'Por qué diseñar antes de programar ahorra reescritura después'),
('TESTB', 5, 'Testing básico', 'Fundamentos', 'Escribir tests para código ya hecho', '3 tests para una función existente', 'Un cambio rompe un test sin que se note al principio', 'Por qué un test que nunca falla no sirve'),
('ERR', 6, 'Manejo de errores y logging', 'Fundamentos', 'Capturar y loguear errores con contexto', 'Capturar errores de una función y loguearlos', 'Un error silencioso esconde el problema real', 'Fallar rápido vs fallar en silencio'),
('ALG', 52, 'Algoritmos y complejidad', 'Fundamentos', 'Entender por qué una solución es más rápida que otra', 'Comparar dos formas de resolver el mismo problema (fuerza bruta vs optimizada)', 'La solución funciona con 10 datos pero se cuelga con 100.000', 'Qué es la complejidad (Big-O) y por qué importa antes de escalar'),
('SQL', 7, 'SQL básico', 'Bases de datos', 'Consultar y modificar datos con SQL', 'SELECT/INSERT/UPDATE sobre tabla de productos', 'Query sin WHERE que borra de más', 'Por qué siempre revisar el WHERE antes de ejecutar'),
('MOD', 8, 'Modelado relacional', 'Bases de datos', 'Diseñar tablas relacionadas correctamente', 'Tablas para un sistema de pedidos', 'Datos duplicados por mal diseño', 'Normalización y claves foráneas'),
('TRX', 9, 'Transacciones', 'Bases de datos', 'Garantizar operaciones todo-o-nada', 'Transferencia de saldo entre dos cuentas', 'La transferencia se corta a mitad de camino', 'Atomicidad'),
('CONC', 10, 'Concurrencia en bases de datos', 'Bases de datos', 'Evitar inconsistencias con usuarios simultáneos', 'Endpoint de compra con control de stock', '100 compras simultáneas del último producto', 'Race conditions, locks (FOR UPDATE)'),
('HTTP', 11, 'HTTP básico', 'Backend', 'Entender el protocolo detrás de toda API', 'Identificar método, headers y body en requests reales', 'Request mal formado, código de estado incorrecto', 'Qué significa cada código HTTP'),
('REST', 12, 'APIs REST', 'Backend', 'Diseñar un CRUD completo', 'CRUD de tareas', 'Endpoint que acepta cualquier dato sin validar', 'Diseño de recursos, verbos HTTP correctos'),
('AUTH', 13, 'Autenticación', 'Backend', 'Proteger endpoints con login real', 'Login con token JWT', 'Token robado o expirado usado para acceder', 'Expiración, refresh tokens'),
('ORM', 14, 'ORMs', 'Backend', 'Reemplazar SQL crudo por un ORM', 'CRUD de tareas con ORM', 'N+1 queries sin darse cuenta', 'Eager loading, costos ocultos del ORM'),
('TEST', 15, 'Testing backend', 'Backend', 'Probar una API completa', 'Suite de tests de integración', 'Test pasa en local pero falla en CI', 'Entornos inconsistentes, datos de prueba mal aislados'),
('ASYNC', 16, 'Colas y procesamiento asíncrono', 'Backend', 'No bloquear al usuario con tareas lentas', 'Enviar email de confirmación sin bloquear la respuesta', 'La cola se satura y los mensajes se pierden', 'Reintentos, dead-letter queue'),
('HTML', 17, 'HTML y CSS', 'Frontend', 'Maquetar una interfaz', 'Página de perfil de usuario', 'Se rompe en pantallas chicas', 'Diseño responsive'),
('JS', 18, 'JavaScript básico', 'Frontend', 'Validar datos del lado del cliente', 'Validar un formulario antes de enviarlo', 'Usuario ingresa datos inesperados', 'Validación cliente vs servidor'),
('DOM', 19, 'DOM y eventos', 'Frontend', 'Actualizar la página sin recargar', 'Lista de tareas dinámica', 'Clics rápidos generan tareas duplicadas', 'Debounce'),
('FE', 20, 'Frameworks frontend', 'Frontend', 'Reconstruir la UI con React', 'Lista de tareas en React', 'El componente se re-renderiza infinito', 'Dependencias mal declaradas en efectos'),
('STATE', 21, 'Estado y componentes', 'Frontend', 'Compartir estado entre pantallas', 'Estado de usuario logueado compartido', 'Dos componentes muestran datos distintos', 'Fuente única de verdad'),
('SO', 22, 'Sistemas operativos básico', 'Sistemas', 'Manejar procesos desde la terminal', 'Manejar procesos y archivos por terminal', 'Proceso que no termina y consume memoria', 'Qué es un proceso, cómo matarlo bien'),
('PROC', 23, 'Procesos y aislamiento', 'Sistemas', 'Correr apps sin que choquen entre sí', 'Dos versiones de la misma app sin conflicto', 'Conflicto de puertos, dependencias incompatibles', 'Qué problema resuelve el aislamiento'),
('RED', 24, 'Redes básicas', 'Sistemas', 'Conectar dos servicios entre sí', 'Dos servicios que se comunican en red', 'Uno no encuentra al otro', 'Resolución de direcciones y puertos'),
('SEG', 25, 'Seguridad básica', 'Sistemas', 'Proteger un endpoint sensible', 'Endpoint con permisos', 'Acceso sin autorización, inyección SQL básica', 'Mínimo privilegio, sanitización de inputs'),
('GIT', 26, 'Git básico', 'DevOps', 'Versionar cambios de código', 'Primer commit e historial', 'Commit que borra trabajo de otro', 'Por qué revisar antes de commit/push'),
('GITCOL', 27, 'Git colaborativo (branches y PRs)', 'DevOps', 'Trabajar en equipo sin pisarse', 'Dos personas con ramas separadas', 'Conflicto de merge', 'Cómo resolver un conflicto sin perder trabajo'),
('CI', 28, 'CI/CD', 'DevOps', 'Automatizar tests en cada push', 'Pipeline que corre tests automáticamente', 'Pipeline en verde pero el deploy falla igual', 'Tests pasan ≠ listo para producción'),
('DOCK', 29, 'Contenedores', 'DevOps', 'Empaquetar la app para que corra igual en todos lados', 'Contenedor de la API', 'Funciona en mi máquina pero no en el contenedor', 'Dependencias implícitas del entorno local'),
('CLOUD', 30, 'Cloud y despliegue', 'DevOps', 'Desplegar en un servicio real', 'Deploy de la API en cloud', 'El servicio se cae bajo tráfico real', 'Límites de recursos, autoescalado'),
('MON', 31, 'Monitoreo y logs', 'DevOps', 'Ver errores y tiempos de respuesta', 'Dashboard simple con errores', 'Error crítico pasa desapercibido por falta de alertas', 'Qué métricas importan de verdad'),
('PAT', 32, 'Patrones de diseño', 'Arquitectura', 'Refactorizar código repetido con criterio', 'Aplicar un patrón (Factory, Strategy)', 'Patrón aplicado donde no hace falta', 'Cuándo un patrón ayuda vs cuándo sobre-ingenieriza'),
('MICRO', 33, 'Microservicios', 'Arquitectura', 'Separar una API en servicios independientes', 'Separar usuarios y pedidos en 2 servicios', 'Un servicio cae y tumba a los demás', 'Acoplamiento, tolerancia a fallos'),
('ESCALA', 34, 'Escalabilidad', 'Arquitectura', 'Soportar 10x el tráfico actual', 'Escalar el sistema actual', 'Cuello de botella en la base de datos', 'Caché, réplicas, particionamiento'),
('DIST', 35, 'Sistemas distribuidos', 'Arquitectura', 'Sincronizar datos entre instancias', 'Sincronizar 2 instancias del mismo servicio', 'Datos inconsistentes entre instancias', 'Consistencia eventual'),
('COMP', 36, 'Competencia: Ingeniero de Software base', 'Competencia', 'Validar dominio integral de las 7 ramas', NULL, NULL, NULL),
('B01', 39, 'Célula vegetal', 'Biología vegetal', 'Identificar estructuras y su función', 'Identificar cloroplasto, pared celular, vacuola en muestras reales', 'Célula dañada o en estado atípico, difícil de clasificar', 'Qué estructura cambia según la función (fotosíntesis vs almacenamiento)'),
('B02', 40, 'Fotosíntesis', 'Biología vegetal', 'Entender cómo la planta produce energía con luz', 'Medir producción de oxígeno bajo distinta luz', 'Planta en oscuridad total o luz excesiva', 'Por qué existe un punto óptimo de luz'),
('B03', 41, 'Absorción de luz y clorofila', 'Biología vegetal', 'Entender qué luz usa la planta y cuál refleja', 'Comparar qué colores absorbe una hoja vs cuáles refleja', 'Hoja que refleja distinto a lo esperado (estrés o enfermedad)', 'Por qué el verde es el color que menos se absorbe'),
('B04', 42, 'Estrés hídrico y nutricional en plantas', 'Biología vegetal', 'Distinguir tipos de estrés en una planta', 'Comparar planta bien regada vs con falta de agua', 'Síntomas visuales ambiguos (¿agua o nutrientes?)', 'Qué indicadores distinguen un tipo de estrés de otro'),
('B05', 43, 'Ciclo de crecimiento y fenología vegetal', 'Biología vegetal', 'Entender las etapas de crecimiento de una planta', 'Registrar etapas de crecimiento en el tiempo', 'Una etapa se salta o se retrasa por condiciones externas', 'Qué factores externos alteran el ciclo esperado'),
('FZ01', 44, 'Espectro electromagnético', 'Física de la luz', 'Distinguir qué luz es visible y cuál no', 'Identificar qué rango de luz es visible vs infrarrojo', 'Instrumento que "ve" en un rango equivocado', 'Por qué el infrarrojo cercano es clave para medir vegetación'),
('FZ02', 45, 'Reflectancia y absorción de luz en materiales', 'Física de la luz', 'Medir cómo distintas superficies responden a la luz', 'Medir cuánta luz refleja hoja, tierra y agua', 'Superficie mojada o con polvo que altera la lectura', 'Por qué hay que calibrar el instrumento antes de medir'),
('D01', 46, 'Estadística aplicada a datos biológicos', 'Datos y visión', 'Sacar conclusiones confiables de mediciones biológicas', 'Calcular promedio, varianza y outliers en mediciones de plantas', 'Un sensor descalibrado distorsiona todo el promedio', 'Por qué hay que filtrar outliers antes de concluir'),
('D02', 47, 'Sensores e imágenes multiespectrales', 'Datos y visión', 'Interpretar imágenes que combinan varias bandas de luz', 'Interpretar una imagen que combina luz visible + infrarroja', 'Imagen borrosa o mal calibrada', 'Cómo se combina cada banda en una imagen útil'),
('D03', 48, 'Índices de vegetación (NDVI)', 'Datos y visión', 'Medir la salud de un cultivo desde una imagen', 'Calcular NDVI a partir de una imagen de cultivo', 'Nubes o sombras que distorsionan el índice', 'Por qué hay que filtrar o normalizar antes de confiar en el número'),
('D04', 49, 'Visión por computadora básica', 'Datos y visión', 'Detectar formas en una imagen con código', 'Programa que detecta el contorno de una hoja en una foto', 'Hoja superpuesta con otra, fondo con color parecido', 'Por qué el contraste y el fondo importan tanto como el algoritmo'),
('D05', 50, 'Modelos de clasificación aplicados a plantas', 'Datos y visión', 'Distinguir planta sana de planta con estrés, automáticamente', 'Clasificador simple sano/estresado', 'El modelo entrenado solo con buena luz falla con luz distinta', 'Por qué hace falta variedad de datos, no solo cantidad'),
('CRUCE1', 51, 'Competencia cruzada: Reconocimiento y optimización de plantas con IA', 'Competencia cruzada', 'Detectar estrés hídrico en un cultivo a partir de fotos', 'Calcular NDVI de un set de fotos y entrenar el clasificador', 'Fotos con nubes, sombras parciales, plantas sanas mal iluminadas', 'Por qué la luz y las sombras distorsionan la lectura, y cómo corregirlo')
on conflict (id) do update set numero=excluded.numero, nombre=excluded.nombre, rama=excluded.rama, objetivo=excluded.objetivo, construir=excluded.construir, romper=excluded.romper, resolver=excluded.resolver;

insert into aristas (origen, destino, tipo, fuente, confianza) values
('L', 'V', 'prerrequisito', 'graph-data.json', 'alto'),
('V', 'F', 'prerrequisito', 'graph-data.json', 'alto'),
('F', 'POO', 'prerrequisito', 'graph-data.json', 'alto'),
('POO', 'REQ', 'prerrequisito', 'graph-data.json', 'alto'),
('REQ', 'DIS', 'prerrequisito', 'graph-data.json', 'alto'),
('F', 'TESTB', 'prerrequisito', 'graph-data.json', 'alto'),
('F', 'ERR', 'prerrequisito', 'graph-data.json', 'alto'),
('POO', 'ERR', 'prerrequisito', 'graph-data.json', 'alto'),
('F', 'ALG', 'prerrequisito', 'graph-data.json', 'alto'),
('L', 'SQL', 'prerrequisito', 'graph-data.json', 'alto'),
('SQL', 'MOD', 'prerrequisito', 'graph-data.json', 'alto'),
('MOD', 'TRX', 'prerrequisito', 'graph-data.json', 'alto'),
('TRX', 'CONC', 'prerrequisito', 'graph-data.json', 'alto'),
('HTTP', 'REST', 'prerrequisito', 'graph-data.json', 'alto'),
('F', 'REST', 'prerrequisito', 'graph-data.json', 'alto'),
('REST', 'AUTH', 'prerrequisito', 'graph-data.json', 'alto'),
('MOD', 'ORM', 'prerrequisito', 'graph-data.json', 'alto'),
('POO', 'ORM', 'prerrequisito', 'graph-data.json', 'alto'),
('REST', 'TEST', 'prerrequisito', 'graph-data.json', 'alto'),
('TESTB', 'TEST', 'prerrequisito', 'graph-data.json', 'alto'),
('REST', 'ASYNC', 'prerrequisito', 'graph-data.json', 'alto'),
('JS', 'DOM', 'prerrequisito', 'graph-data.json', 'alto'),
('HTML', 'DOM', 'prerrequisito', 'graph-data.json', 'alto'),
('DOM', 'FE', 'prerrequisito', 'graph-data.json', 'alto'),
('FE', 'STATE', 'prerrequisito', 'graph-data.json', 'alto'),
('L', 'SO', 'prerrequisito', 'graph-data.json', 'alto'),
('SO', 'PROC', 'prerrequisito', 'graph-data.json', 'alto'),
('HTTP', 'RED', 'prerrequisito', 'graph-data.json', 'alto'),
('RED', 'SEG', 'prerrequisito', 'graph-data.json', 'alto'),
('AUTH', 'SEG', 'prerrequisito', 'graph-data.json', 'alto'),
('GIT', 'GITCOL', 'prerrequisito', 'graph-data.json', 'alto'),
('GITCOL', 'CI', 'prerrequisito', 'graph-data.json', 'alto'),
('TEST', 'CI', 'prerrequisito', 'graph-data.json', 'alto'),
('PROC', 'DOCK', 'prerrequisito', 'graph-data.json', 'alto'),
('DOCK', 'CLOUD', 'prerrequisito', 'graph-data.json', 'alto'),
('CLOUD', 'MON', 'prerrequisito', 'graph-data.json', 'alto'),
('ERR', 'MON', 'prerrequisito', 'graph-data.json', 'alto'),
('POO', 'PAT', 'prerrequisito', 'graph-data.json', 'alto'),
('DIS', 'PAT', 'prerrequisito', 'graph-data.json', 'alto'),
('REST', 'MICRO', 'prerrequisito', 'graph-data.json', 'alto'),
('DOCK', 'MICRO', 'prerrequisito', 'graph-data.json', 'alto'),
('ASYNC', 'MICRO', 'prerrequisito', 'graph-data.json', 'alto'),
('MICRO', 'ESCALA', 'prerrequisito', 'graph-data.json', 'alto'),
('CONC', 'ESCALA', 'prerrequisito', 'graph-data.json', 'alto'),
('ALG', 'ESCALA', 'prerrequisito', 'graph-data.json', 'alto'),
('ESCALA', 'DIST', 'prerrequisito', 'graph-data.json', 'alto'),
('PAT', 'COMP', 'prerrequisito', 'graph-data.json', 'alto'),
('MICRO', 'COMP', 'prerrequisito', 'graph-data.json', 'alto'),
('CI', 'COMP', 'prerrequisito', 'graph-data.json', 'alto'),
('SEG', 'COMP', 'prerrequisito', 'graph-data.json', 'alto'),
('MON', 'COMP', 'prerrequisito', 'graph-data.json', 'alto'),
('B01', 'B02', 'prerrequisito', 'graph-data.json', 'alto'),
('B02', 'B03', 'prerrequisito', 'graph-data.json', 'alto'),
('B03', 'B04', 'prerrequisito', 'graph-data.json', 'alto'),
('B02', 'B05', 'prerrequisito', 'graph-data.json', 'alto'),
('FZ01', 'FZ02', 'prerrequisito', 'graph-data.json', 'alto'),
('L', 'D01', 'prerrequisito', 'graph-data.json', 'alto'),
('FZ02', 'D02', 'prerrequisito', 'graph-data.json', 'alto'),
('B03', 'D03', 'prerrequisito', 'graph-data.json', 'alto'),
('D02', 'D03', 'prerrequisito', 'graph-data.json', 'alto'),
('F', 'D04', 'prerrequisito', 'graph-data.json', 'alto'),
('POO', 'D04', 'prerrequisito', 'graph-data.json', 'alto'),
('D02', 'D04', 'prerrequisito', 'graph-data.json', 'alto'),
('D01', 'D05', 'prerrequisito', 'graph-data.json', 'alto'),
('D04', 'D05', 'prerrequisito', 'graph-data.json', 'alto'),
('D03', 'D05', 'prerrequisito', 'graph-data.json', 'alto'),
('B04', 'CRUCE1', 'prerrequisito', 'graph-data.json', 'alto'),
('B05', 'CRUCE1', 'prerrequisito', 'graph-data.json', 'alto'),
('D03', 'CRUCE1', 'prerrequisito', 'graph-data.json', 'alto'),
('D05', 'CRUCE1', 'prerrequisito', 'graph-data.json', 'alto')
on conflict (origen, destino) do nothing;
