"use client";
import { useState } from "react";
type Props={onComplete:()=>void};
export default function AprenderPOO({onComplete}:Props){const [step,setStep]=useState(0);const [answer,setAnswer]=useState<number|null>(null);const next=()=>{if(answer===null)return;setAnswer(null);setStep(s=>s+1)};const choice=(i:number)=>setAnswer(i);const data=[
["Una entidad tiene estado y comportamiento","usuario.nombre + usuario.comprar()","¿Qué representa mejor una clase?",["Un modelo que agrupa datos y comportamiento","Una lista de números","Un archivo que solo guarda texto"],0,"Separar el modelo de su uso"],
["Los objetos son instancias","Usuario A y Usuario B pueden tener datos distintos","¿Qué ventaja tiene crear objetos desde una clase?",["Cada objeto puede mantener su propio estado","Todos deben tener exactamente los mismos datos","No pueden tener métodos"],0,"Estado independiente"],
["La composición conecta responsabilidades","Pedido contiene un Usuario en lugar de heredar de él","¿Cuándo es más natural composición?",["Cuando una entidad tiene otra","Cuando todo debe heredar de todo","Cuando no existen relaciones"],0,"Composición"],
["La herencia puede introducir supuestos","Animal → Ave → Pingüino puede romper una operación que supone volar","¿Qué riesgo muestra el ejemplo?",["Una subclase puede no cumplir una suposición de la clase base","La herencia siempre es obligatoria","Los objetos dejan de existir"],0,"Herencia"],
["Diseñar antes evita acoplamiento innecesario","Usuario y Pedido colaboran mediante responsabilidades claras","¿Qué principio conviene conservar?",["Cada clase debe tener una responsabilidad comprensible","Una clase debe hacer todo","Duplicar la lógica en cada objeto"],0,"Responsabilidad"]];
if(step>=data.length)return <div className="learn-experience"><div className="learn-icon">🧱</div><div className="sheet-title">Puedes modelar objetos sin mezclar responsabilidades</div><div className="learn-summary"><div><span>01</span><b>Clase</b><p>define estructura y comportamiento</p></div><div><span>02</span><b>Objeto</b><p>mantiene su propio estado</p></div><div><span>03</span><b>Composición</b><p>conecta entidades sin herencia innecesaria</p></div></div><button className="btn" onClick={onComplete}>Empezar práctica →</button></div>;
const d=data[step];return <div className="learn-experience"><div className="learn-top"><div><div className="sheet-eyebrow">APRENDER · {step+1}/{data.length}</div><div className="learn-progress"><div style={{width:`${(step+1)/data.length*100}%`}}/></div></div><div className="learn-tag">objetos + diseño</div></div><div className="learn-icon">🧱</div><div className="sheet-title">{d[0]}</div><p className="learn-text">{d[1]}</p><p className="learn-question">{d[2]}</p><div className="learn-choice-grid">{(d[3] as string[]).map((x,i)=><button key={x} className={`learn-choice ${answer===i?"selected":""}`} onClick={()=>choice(i)}>{x}</button>)}</div><button className="btn" disabled={answer!==0} onClick={next}>{step===data.length-1?"Consolidar idea →":"Continuar →"}</button></div>}
