"use client";
import { useMemo,useState } from "react";
type Props={onFinish:(correctas:number,total:number)=>void};
type Item={id:string;title:string;prompt:string;options:string[];correct:number;skill:string};
const ITEMS:Item[]=[
{id:"class",title:"01 · Clase",prompt:"¿Qué agrupa una clase?",options:["Datos y comportamiento relacionados","Solo colores","Solo archivos"],correct:0,skill:"clases"},
{id:"state",title:"02 · Estado",prompt:"¿Qué permite una instancia?",options:["Mantener su propio estado","Obligar a todas a compartir datos","Eliminar métodos"],correct:0,skill:"objetos"},
{id:"composition",title:"03 · Composición",prompt:"¿Cuándo encaja composición?",options:["Cuando una entidad contiene o usa otra","Cuando todo debe heredar","Cuando no hay relación"],correct:0,skill:"composicion"},
{id:"inheritance",title:"04 · Herencia",prompt:"¿Qué peligro aparece con una abstracción demasiado fuerte?",options:["Una subclase puede no cumplir las suposiciones de la base","El código siempre es más corto","No se pueden crear objetos"],correct:0,skill:"herencia"},
{id:"responsibility",title:"05 · Responsabilidad",prompt:"¿Qué diseño es más mantenible?",options:["Clases con responsabilidades claras","Una clase que hace todo","Duplicar cada comportamiento"],correct:0,skill:"responsabilidad"}
];
export default function EvaluacionPOO({onFinish}:Props){const [answers,setAnswers]=useState<Record<string,number>>({});const [submitted,setSubmitted]=useState(false);const complete=ITEMS.every(i=>answers[i.id]!==undefined);const score=useMemo(()=>ITEMS.reduce((s,i)=>s+(answers[i.id]===i.correct?1:0),0),[answers]);const failed=useMemo(()=>[...new Set(ITEMS.filter(i=>answers[i.id]!==i.correct).map(i=>i.skill))],[answers]);function finish(){if(!complete||submitted)return;setSubmitted(true);try{localStorage.setItem("helikon:last-failed-skills",JSON.stringify(failed))}catch{}onFinish(score,ITEMS.length)}return <div className="learn-experience"><div className="learn-top"><div><div className="sheet-eyebrow">EVALUACIÓN · RETO 04</div><div className="learn-progress"><div style={{width:`${Object.keys(answers).length/ITEMS.length*100}%`}}/></div></div><div className="learn-tag">sin pistas</div></div><div className="learn-icon">🧪</div><div className="sheet-title">Demuestra que puedes modelar objetos</div><p className="learn-text">Debes reconocer clases, estado, composición, herencia y responsabilidades.</p><div className="question-list">{ITEMS.map(item=><div className="question" key={item.id}><div className="question-n">{item.title}</div><div className="question-text">{item.prompt}</div><div className="options">{item.options.map((o,j)=><button key={o} className={`option ${answers[item.id]===j?"selected":""}`} disabled={submitted} onClick={()=>!submitted&&setAnswers(a=>({...a,[item.id]:j}))}>{o}</button>)}</div></div>)}</div><div className="evidence-note">Las habilidades fallidas quedan registradas para dirigir el refuerzo.</div><button className="btn" disabled={!complete||submitted} onClick={finish}>Demostrar competencia →</button></div>}
