"use client";

import { useMemo, useState } from "react";
type Props={onFinish:(correctas:number,total:number)=>void};
type Item={id:string;title:string;prompt:string;options:string[];correct:number;skill:string};
const ITEMS:Item[]=[
{id:"responsibility",title:"01 · Responsabilidad",prompt:"¿Qué describe mejor una función bien separada?",options:["Una responsabilidad concreta que puede reutilizarse","Todo el programa en una sola función","Una función que hace tareas sin relación"],correct:0,skill:"funciones"},
{id:"list",title:"02 · Datos",prompt:"¿Qué estructura representa una colección de pedidos?",options:["Una lista","Una condición","Un string obligatorio"],correct:0,skill:"listas"},
{id:"empty",title:"03 · Caso vacío",prompt:"Una función recibe []. ¿Qué comportamiento es razonable para un total?",options:["Devolver 0","Inventar un pedido","Fallarse siempre"],correct:0,skill:"listas"},
{id:"types",title:"04 · Tipos",prompt:"Una lista contiene 10 y '20'. ¿Qué debe hacer una función robusta?",options:["Validar compatibilidad antes de operar","Sumarlos sin comprobar","Eliminar el número 10"],correct:0,skill:"tipos"},
{id:"duplicate",title:"05 · Duplicados",prompt:"Un pedido aparece dos veces. ¿Qué riesgo existe?",options:["Contarlo dos veces","Que se convierta en una función","Que desaparezca automáticamente"],correct:0,skill:"duplicados"}
];
export default function EvaluacionFunciones({onFinish}:Props){const [answers,setAnswers]=useState<Record<string,number>>({});const [submitted,setSubmitted]=useState(false);const complete=ITEMS.every(i=>answers[i.id]!==undefined);const score=useMemo(()=>ITEMS.reduce((s,i)=>s+(answers[i.id]===i.correct?1:0),0),[answers]);const failed=useMemo(()=>[...new Set(ITEMS.filter(i=>answers[i.id]!==i.correct).map(i=>i.skill))],[answers]);function finish(){if(!complete||submitted)return;setSubmitted(true);try{localStorage.setItem("helikon:last-failed-skills",JSON.stringify(failed))}catch{}onFinish(score,ITEMS.length)}return <div className="learn-experience"><div className="learn-top"><div><div className="sheet-eyebrow">EVALUACIÓN · RETO 03</div><div className="learn-progress"><div style={{width:`${Object.keys(answers).length/ITEMS.length*100}%`}}/></div></div><div className="learn-tag">sin pistas</div></div><div className="learn-icon">🧪</div><div className="sheet-title">Demuestra que puedes procesar datos</div><p className="learn-text">Debes separar responsabilidades, trabajar con listas y reconocer casos que pueden romper una función.</p><div className="question-list">{ITEMS.map(item=><div className="question" key={item.id}><div className="question-n">{item.title}</div><div className="question-text">{item.prompt}</div><div className="options">{item.options.map((o,j)=><button key={o} className={`option ${answers[item.id]===j?"selected":""}`} disabled={submitted} onClick={()=>!submitted&&setAnswers(a=>({...a,[item.id]:j}))}>{o}</button>)}</div></div>)}</div><div className="evidence-note">Las habilidades que fallen quedan registradas para generar refuerzo dirigido.</div><button className="btn" disabled={!complete||submitted} onClick={finish}>Demostrar competencia →</button></div>}
