"use client";

import { useMemo, useState } from "react";

type Props = { skills: string[]; onComplete: () => void };
const ITEMS = [
  { skill: "listas", title: "Lista vacía", prompt: "Una función procesa una lista de pedidos. ¿Qué debe hacer si recibe []?", options: ["Fallar siempre", "Devolver un resultado válido para lista vacía", "Inventar un pedido"], correct: 1 },
  { skill: "funciones", title: "Responsabilidad", prompt: "¿Por qué separar el cálculo del total en una función?", options: ["Para duplicar código", "Para aislar una responsabilidad y poder probarla", "Para evitar usar datos"], correct: 1 },
  { skill: "tipos", title: "Tipos mezclados", prompt: "Una lista contiene 10 y '20'. ¿Qué debe comprobarse antes de sumar?", options: ["Que los datos sean compatibles", "Que la lista tenga 100 elementos", "Nada"], correct: 0 },
  { skill: "duplicados", title: "Duplicados", prompt: "Si un pedido aparece dos veces, ¿qué riesgo existe al sumar directamente la lista?", options: ["Contarlo dos veces", "Que desaparezca automáticamente", "Que se convierta en una función"], correct: 0 }
];
export default function ReforzarFunciones({skills,onComplete}:Props){const active=useMemo(()=>{const selected=skills.map(s=>ITEMS.find(i=>i.skill===s)).filter(Boolean) as typeof ITEMS;return selected.length?selected:ITEMS.slice(0,1)},[skills]);const [step,setStep]=useState(0);const [answer,setAnswer]=useState<number|null>(null);const current=active[step];const correct=answer===current.correct;function next(){if(!correct)return;if(step===active.length-1){try{localStorage.removeItem("helikon:last-failed-skills")}catch{}onComplete();return;}setStep(s=>s+1);setAnswer(null)}return <div className="learn-experience"><div className="learn-top"><div><div className="sheet-eyebrow">REFUERZO ADAPTATIVO · {step+1}/{active.length}</div><div className="learn-progress"><div style={{width:`${((step+1)/active.length)*100}%`}}/></div></div><div className="learn-tag">habilidad detectada</div></div><div className="learn-icon">🔧</div><div className="sheet-title">{current.title}</div><p className="learn-text">El ejercicio cambia, pero conserva la habilidad que Helikon detectó como débil.</p><div className="learn-challenge"><b>HABILIDAD · {current.skill}</b><br/>{current.prompt}</div><div className="learn-choice-grid">{current.options.map((o,i)=><button key={o} className={`learn-choice ${answer===i?"selected":""}`} onClick={()=>setAnswer(i)}>{o}</button>)}</div>{answer!==null&&<div className={`learn-feedback ${correct?"good":"bad"}`}>{correct?"✓ Evidencia recuperada.":"! Revisa el comportamiento antes de continuar."}</div>}<button className="btn" disabled={!correct} onClick={next}>{step===active.length-1?"Volver a demostrar →":"Siguiente refuerzo →"}</button></div>}
